### ISSUE TITLE
What is the parametres 'uniqID' and 'featureCollection'

### ISSUE THREAD

**Issue by LiliGuimaraes** [eMapR/TimeSync-Plus#1]
Hellow,
I'm newbie in this, so I don't understand what  exactly is:
 1 - 'lcb.props['featureID'] = 'uniqID' (register as  this is a field name in the uploaded asset for unique polygons), and either what is
2 -  "lcb.props['featureCollection']" (register as  "this comes from asset upload") .

The last one is the the polygon of my interest area?

**Comment by LiliGuimaraes** [comment]
Hello again,
I get the error 
```
Traceback (most recent call last):
  File "/home/lili/work/mapbiomas/landtrend/TS-Plus/create_sql_db_plus.py", line 283, in <module>
    main()
  File "/home/lili/work/mapbiomas/landtrend/TS-Plus/create_sql_db_plus.py", line 227, in main
    obser_val_dict = observation_value_dict(startYear, end, data) # chage here vvv
  File "/home/lili/work/mapbiomas/landtrend/TS-Plus/create_sql_db_plus.py", line 183, in observation_value_dict
    values = [templistB[i][0], templistB[i][1], templistB[i][2], templistB[i][3], templistB[i][4], templistB[i][5], 0, '217', int(templistB[i][6]), templistB[i][7].encode("utf-8"), 1100, 'null', 'LT5', 10000, templistB[i][8], 0, 0, 0, 999999, 'another.png', templistB[i][8]]	
IndexError: list index out of range
```
My starting year is 1985 to 1995, from 01-09 to 31-03, ant that's the code tha in GEE that I used to dowloand the images.[https://code.earthengine.google.com/32b19abb033b3bc366f7a9745171f44f]
I did rigth?

**Comment by LiliGuimaraes** [comment]
Hello again-and-again,
When running the command `"​ python \full\path\to\create_sql_db.py",` (which initially only runs on python2 on Linux because of the current version of Tkinter for Debian), 
the processing breaks from line 240, where specifically the code creates the database by entering SQL commands in tables and columns.
I get the error shows in the print
![run_create_sql_db](https://user-images.githubusercontent.com/19511732/62395241-0bb10700-b546-11e9-8b6f-a35a1d66ac63.png)

**Comment by jdbcode** [comment]
*Comment 1*:

`lcb.props['featureCollection']` should be a `string` describing the path to a vector asset that you uploaded that defines a series of polygons that you want to do TimeSync interpretation for.

`lcb.props['featureID']` should be a `string` that matches the name of a field in the shapefile you uploaded and defined the resulting asset path in the above `lcb.props['featureCollection']`. The values in this field should represent the unique ID for each polygon in the set of polygons you want to do TimeSync interpretation on. A summary statistic will be calculated for all pixels intersecting each unique polygon for each each year in the time series.

*Comment 2*:

@clarype - can you help here (Peter developed the Python script).

*Comment 3*:

@clarype - can you help here (Peter developed the Python script).

It might be helpful for debugging if you can share you scripts and assets with us, if the data are not too large. Send me an email to coordinate sharing and I'll loop Peter in (jstnbraaten@gmail.com).
