### ISSUE TITLE
Tab bar on the right side doesn't appear

### ISSUE THREAD

**Issue by leahlee0731** [eMapR/TimeSync-Plus#5]
Hi Peter and Justin,

Thanks for providing the step-by-step guidance on how to use the TimeSyncPlus App.

Because I am unable to open the link you provide at step 10 (ftp://islay.ceoas.oregonstate.edu/TimeSyncPlus/), so I use the link you provide in the issue #2.  But as in the attached figure, the tab bar on the right side doesn't appear. I didn't make changes to the config file. Do you have any idea of the possible reason? Thanks in advance.
![TimeSyncPlus](https://user-images.githubusercontent.com/59778353/113631922-30715200-9638-11eb-9572-60433b8fcb45.jpg)

Best,
Yang

**Comment by leahlee0731** [comment]
The problem solved. I use another browser instead of Chrome to open the link: ftp://islay.ceoas.oregonstate.edu/TimeSyncPlus/. The app download from this link works well. Thanks.

**Comment by jdbcode** [comment]
Glad to hear you got it working!
