### ISSUE TITLE
The downloaded tif files are with value 0; fail to adjust the StartYear and EndYear

### ISSUE THREAD

**Issue by leahlee0731** [eMapR/TimeSync-Plus#6]
Hi Peter and Justin,

Greetings. As you described in step 10 of this tutorial, I put the database in the same directory as the tiles folder, but no images appear in the bottom "image chip section". So I checked the 4 tif files (i.e., rgb654, rgb543, rgbTC, and rbg432) downloaded from GEE, finding their values are all 0, and the generated images in "tms" file based on Step 6 are also 0. But as you can see from the upper "spectral trajectory" section in the following figure, the "observations.geojson" downloaded from GEE gives me a time series with values.  
![image](https://user-images.githubusercontent.com/59778353/116958077-720d1100-ac67-11eb-952d-d5fa4c835814.png)

Another issue I met was that even though I changed the "StartYear" and "EndYear" in the GEE script (i.e., 2001-2016), the downloaded data started and ended as the parameters you provided (i.e., 1986-2018). 

Thanks for your time and I wonder if you have any ideas for those two problems. The manuscript I used to generate data in GEE is here: https://code.earthengine.google.com/35bb9b1bbc75b9b600c1f6b913bbfa33; and the data downloaded from GEE is here: https://drive.google.com/drive/folders/1eLzUvryi4z2kyVkW9A4BQVkE7ePsGuaV?usp=sharing.

Best,
Yang

**Comment by jdbcode** [comment]
Hi @leahlee0731 thanks for sharing the issues.

Just a warning to let you know I've not worked on this project in a long time and it outside of my current employment responsibilities, so I may not be able to address the issue, or at least maybe not in a timely manner. 

Regarding the zeros from the downloaded GEE data, could you please share your feature collection asset (if possible, or send me a script with a couple points you've placed in the vicinity) so I can try to reproduce: `users/leahleeosu/Disturbance_detection/TSA_SamplePts/TSA_SamplePts_CA`

Regarding the years not matching what you defined: this is a known issue with the `ee-lcb` library that I need to resolve, your issue is applying some pressure for me to do it, I'll try to resolve it this week. Here is a [related issue](https://github.com/jdbcode/ee-rgb-timeseries/issues/2#issuecomment-809569513).

**Comment by leahlee0731** [comment]
Hi @jdbcode, the feature collection is shared now, thanks a lot for the help!

**Comment by jdbcode** [comment]
Thanks!
I just confirmed I can access.

**Comment by leahlee0731** [comment]
Thank you!

**Comment by jdbcode** [comment]
Hi again @leahlee0731 

Sorry to keep requesting that you test things, but I appreciate the help debugging. I think there is some confusion in the script about the aoi - for some operations it is using the ee-lcb default and for others it is using your feature collection. I think that the following script sorts out the confusion. Will you please give it a try:

https://code.earthengine.google.com/b365c74e017dd9f13cdfe3770b54a98f

Note that previously the script was only writing files for a very small area (I think) and your area is relatively large, so it may take a while to run. If you have a feature collection with a smaller extent, it would make testing faster.

**Comment by leahlee0731** [comment]
Hi Justin, thanks a lot for taking time out of your busy schedule!

The downloaded .tifs images are normal now in Matlab, but still no images appear in the bottom "image chip section". I go back to check the generated images in the "tms" file (Step 6 in the tutorial doc), finding they are all 0. Because of my limited experience with python, I am not sure if the issue is in the geojsonToSqlDB_v4.py. Here is the drive link of downloaded files from GEE, I use a smaller area as you suggest: https://drive.google.com/drive/folders/1ZjfhKiwkGSgnONVJK2zZ2kWTxkQ825wU?usp=sharing. 

BTW, I set the start time and end time as 2001 and 2016, respectively, but the "tms" files are from 1986 to 2001 while the annual images in TimeSync are from 2001 to 2016. Thanks again for the help.
![image](https://user-images.githubusercontent.com/59778353/118342752-caa79e00-b4f2-11eb-801b-2cdea3a9db47.png)
![image](https://user-images.githubusercontent.com/59778353/118342736-af3c9300-b4f2-11eb-8769-3c6ff5a926f0.png)

**Comment by leahlee0731** [comment]
Hi Justin, please ignore the previous reply. I used the downloaded .tifs images from the original area and they worked perfectly. The only issue remained is that the downloaded data is from 2001 to 2016, but the generated "tms" files are from 1986 to 2001, so annual images in the TimeSync are only available in 2001. This could be fixed by changing the "tms" file names to their corresponding year, and then the annual images are successfully displayed in the bottom section. Thanks again for all the help!

**Comment by jdbcode** [comment]
Well great! Strange that the year labels start out as 1986 to 2001. I'm curious where it is getting those dates - if it is something from the Earth Engine files downloaded or one of the python script, I can probably fix it.

Are you using a conda environment to run the python scripts? If so, is it an env dedicated to the task? What I'm wanting is the configuration of a known working environment. If possible, can you run...

```
conda env export > timesync_plus_env.yml
```

...and paste the contents of the yml here or submit a PR with the file. In the future if issues come up we can have people setup an environment that we know worked.

**Comment by leahlee0731** [comment]
Hi Justin, thanks! Here is the content in the .yml file:

name: TEST27
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2021.1.19=haa95532_1
  - certifi=2020.6.20=pyhd3eb1b0_3
  - curl=7.65.3=h7a46e7a_0
  - expat=2.2.5=h2880e7c_0
  - freexl=1.0.5=h0c8e037_0
  - gdal=2.2.2=py27h58389d3_1
  - geos=3.6.2=heec837b_2
  - hdf4=4.2.13=hd0a9391_2
  - hdf5=1.10.1=h79de857_2
  - icc_rt=2019.0.0=h0cc432a_1
  - intel-openmp=2020.2=254
  - jpeg=9b=ha175dff_2
  - kealib=1.4.7=h40df8b5_5
  - krb5=1.16.1=h467bc42_7
  - libboost=1.67.0=hab8cdc6_4
  - libcurl=7.65.3=h7a46e7a_0
  - libgdal=2.2.2=h75964b3_1
  - libiconv=1.15=hda2e4ec_7
  - libkml=1.3.0=h7e671d2_4
  - libnetcdf=4.4.1.1=hbbeef04_8
  - libpng=1.6.37=h7a46e7a_0
  - libpq=11.2=h4410098_0
  - libspatialite=4.3.0a=hbf2645c_18
  - libssh2=1.8.2=hcfb25f9_0
  - libtiff=4.0.10=h1c3b264_2
  - libxml2=2.9.9=h325896a_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py27h0b88c2a_0
  - mkl_fft=1.0.15=py27h44c1dab_0
  - numpy=1.16.6=py27hcd21bde_0
  - numpy-base=1.16.6=py27hb1d0314_0
  - openjpeg=2.3.0=h8d199b9_1
  - openssl=1.1.1e=h0c8e037_0
  - pandas=0.24.2=py27hc56fc5f_0
  - pip=19.3.1=py27_0
  - proj4=4.9.3=h3980ba1_7
  - python=2.7.18=hfb89ab9_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - pytz=2021.1=pyhd3eb1b0_0
  - setuptools=44.0.0=py27_0
  - six=1.15.0=pyhd3eb1b0_0
  - sqlite=3.30.1=h0c8e037_0
  - tk=8.6.8=h0c8e037_0
  - vc=9=h7299396_1
  - vs2008_runtime=9.00.30729.1=hfaea7d5_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py27hf04cefb_0
  - xerces-c=3.2.2=hc56fc5f_0
  - xz=5.2.4=h3cc03e0_4
  - zlib=1.2.11=h3cc03e0_3
  - zstd=1.3.7=h1b0e4d7_0
prefix: C:\Softwares\Anaconda\anaconda3\envs\TEST27

BTW, I notice that the zoom level of annual images in the TimeSync is limited to a coarse resolution if I manually change the folder names to their corresponding years, even though the outputs in tms folder give me a zoom level to 13 as I set in step 6. I really appreciate your continuous help.

Best,
Yang

**Comment by jdbcode** [comment]
Thanks for the env yml!

How course, can you send a screenshot? This only happens after you change the folder names?

**Comment by leahlee0731** [comment]
Hi Justin, 

Sorry for the late response. Yes, before I change the folder names to their corresponding years, annual images in the TimeSync are only available in 2001, but they can be zoomed in to a very close distance. 
![image](https://user-images.githubusercontent.com/59778353/118587161-187a0b80-b76a-11eb-8331-0584cdb315ba.png)

When I manually change the folder names, as you can see in the following two screenshots, all the annual images are available, but they can only be seen from a far distance. If I continuously zoom in, then the images in all the windows disappear. 
![image](https://user-images.githubusercontent.com/59778353/118587409-8f170900-b76a-11eb-9de5-61ef37fbbd33.png)
![image](https://user-images.githubusercontent.com/59778353/118587549-d3a2a480-b76a-11eb-88ff-fb56244a2c88.png)

I double-checked the .tms folder to ensure that the zoom level folders were not changed.
![image](https://user-images.githubusercontent.com/59778353/118587833-3f850d00-b76b-11eb-9e2f-204ed920c389.png)

Hope I explained it clearly. Thanks!

Best,
Yang
