### ISSUE TITLE
OperationalError: near "INTOpolygonTable": syntax error

### ISSUE THREAD

**Issue by 103b6060power** [eMapR/TimeSync-Plus#8]
Hello, I don't know how to deal with this problem. I hope to get your help and reply.

The error code is as follows：

runfile('G:/TimeSync-Plus-master_2/project/scripts/geojsonToSqlDB_v4.py', wdir='G:/TimeSync-Plus-master_2/project/scripts')
writing database from G:/TimeSync-Plus-master_2/project/tiles/TimeSync\observations.geojson
Traceback (most recent call last):

  File "G:\TimeSync-Plus-master_2\project\scripts\geojsonToSqlDB_v4.py", line 351, in <module>
    input_values_table(conn, main)

  File "G:\TimeSync-Plus-master_2\project\scripts\geojsonToSqlDB_v4.py", line 78, in input_values_table
    cur.execute(main)

OperationalError: near "INTOpolygonTable": syntax error

The key codes are as follows:
 if len(eval(i)) >= 2:
                
                main = 'INSERT INTO'+i+ '('+e+')  VALUES'+eval(i)+';'
               
              
                if conn is not None:
                     with conn:
                     #inputs values into a table
                         input_values_table(conn, main)

**Comment by 103b6060power** [comment]
This error is displayed if the code looks like this :    (I'm using python3.8)

```
 if len(eval(i)) >= 2:
                
                main = 'INSERT INTO '+i+ '('+e+')  VALUES'+eval(i)+'; '
               
              
                if conn is not None:
                     with conn:
                     #inputs values into a table
                         input_values_table(conn, main)
                else:
                     print("Error! cannot create the database connection.")
```
Error display as:
```
runfile('G:/TimeSync-Plus-master_2/project/scripts/geojsonToSqlDB_v4.py', wdir='G:/TimeSync-Plus-master_2/project/scripts')
writing database from G:/TimeSync-Plus-master_2/project/tiles/TimeSync\observations.geojson
Traceback (most recent call last):

  File "G:\TimeSync-Plus-master_2\project\scripts\geojsonToSqlDB_v4.py", line 351, in <module>
    input_values_table(conn, main)

  File "G:\TimeSync-Plus-master_2\project\scripts\geojsonToSqlDB_v4.py", line 78, in input_values_table
    cur.execute(main)

OperationalError: near "''": syntax error
```

**Comment by clarype** [comment]
Hello, sorry the very late response. The workflow is designed for pythong2.7. Have you tried it with that version of python?
